project_name: sphinx-exporter
release:
  github:
    owner: foxdalas
    name: sphinx_exporter

builds:
  - id: sphinx-exporter
    binary: sphinx-exporter
    goos:
      - linux
    goarch:
      - amd64
      - arm64
dockers:
  - id: sphinx-exporter-docker-amd64
    goos: linux
    goarch: amd64
    ids:
      - sphinx-exporter
    image_templates:
      - "foxdalas/sphinx-exporter:v{{ .Version }}-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
    use: buildx
  - id: sphinx-exporter-docker-arm64
    goos: linux
    goarch: arm64
    ids:
      - sphinx-exporter
    image_templates:
      - "foxdalas/sphinx-exporter:v{{ .Version }}-arm64"
    build_flag_templates:
      - "--platform=linux/arm64"
    use: buildx
docker_manifests:
  - name_template: foxdalas/sphinx-exporter:v{{ .Version }}
    image_templates:
      - foxdalas/sphinx-exporter:v{{ .Version }}-amd64
      - foxdalas/sphinx-exporter:v{{ .Version }}-arm64
