project_name: sphinx-exporter
release:
  github:
    owner: foxdalas
    name: sphinx_exporter

builds:
  - id: sphinx-exporter
    binary: sphinx-exporter
    goos:
      - linux
    goarch:
      - amd64
      - arm64
dockers:
  - image_templates:
      - "foxdalas/sphinx-exporter:{{ .Version }}-amd64"
    use: buildx
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"
  - image_templates:
      - "foxdalas/sphinx-exporter:{{ .Version }}-arm64v8"
    use: buildx
    goarch: arm64
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/arm64/v8"
docker_manifests:
  - id: sphinx-exporter
    name_template: foxdalas/sphinx-exporter:{{ .Version }}
    image_templates:
      - foxdalas/sphinx-exporter:{{ .Version }}-amd64
      - foxdalas/sphinx-exporter:{{ .Version }}-arm64v8
    use: docker
