name: "build-and-test"
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Go mod download
      run: go mod download

    - uses: Jerome1337/gofmt-action@v1.0.4
      with:
        gofmt-path: '.'
        gofmt-flags: '-l -d'

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v4
      with:
        version: v1.43
        skip-go-installation: true
        skip-pkg-cache: true

    - name: Test
      run: go test ./...

    - name: Go build
      run: go build .


    - uses: meeDamian/sync-readme@v1.0.6
      with:
        user: ${{ secrets.DOCKERHUB_USERNAME }}
        pass: ${{ secrets.DOCKERHUB_TOKEN }}
        slug: foxdalas/sphinx-exporter
        readme: ./README.md

#  tests:
#    needs: build
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        sphinx-version: [4.5.4, 2.4.3, 4.4.0]
#
#    steps:
#      - uses: actions/checkout@v4
#
#      - name: Go mod download
#        run: go mod download
#
#      - name: Test
#        run: go test ./...
